### PR TITLE
Update Italian Installer language

### PR DESCRIPTION
**Pull request by bovirus**
Please take care that github report the t file is code as ISO8859.
For me should be as UTF-8

### CODE REVIEW

**Comment by bovirus** [comment]
@sdottaka

Please chek the problem about etxt coding (ISO8859 / UTF8)

**Comment by sdottaka** [comment]
Thank you for the PR!
I think that the file encoding of Italian.isl should be CP-1252(ISO-8859-1) because LanguageCodePage in Italian.isl is 1252. 
There is also a way to change LanguageCodePage to 65001 (UTF-8), but I'm not yet convinced that it won't cause a problem.
So I will change the file encoding from UTF-8 to CP1252.
However, I want to make all .isl files UTF-8, so I might change Italian.isl to UTF-8 later.

**Comment by bovirus** [comment]
@sdottaka 

Please take care about accented letter (like àèìòù).
If you sue your installer in Windows Vista/Seven etc the standard is not CP-1252 (for ANIS/DOS) but it's Unicode,

A similar problem (coding CP-1252 vs. UTF-8) appear in the past in Inno Setup github repository  (that in the past used ANSI CP-1252 and now use UTF-8).
 
if you sent an email to roberto . boriotti at canon - europe . com I can reply with some additional resources like

Readme (Italian)
Italian language updated.

The info in this page

http://winmerge.org/translations/?lang=en

seems not updated.
The Italian language is 100% translated.

Thanks.

**Comment by bovirus** [comment]
@sdottaka

New PR

https://github.com/WinMerge/winmerge-v2/pull/165

with changes for Italian language about

Readme
shell extension
installer script
GUI

**Comment by sdottaka** [comment]
> If you can make a temporary installer rebuild I can check the Italian update about accented letters.

You can download the latest installer from:
https://ci.appveyor.com/project/sdottaka/winmerge/builds/26314560/artifacts

You can also download the installer that is not changed to CP-1252 from:
https://ci.appveyor.com/project/sdottaka/winmerge/builds/26314484/artifacts

**Comment by bovirus** [comment]
@sdottaka 

Thanks for the new installer.

File: https://ci.appveyor.com/project/sdottaka/winmerge/builds/26314560/artifacts
This installer is OK about accented letters.

File: https://ci.appveyor.com/project/sdottaka/winmerge/builds/26314484/artifacts
This installer seems not OK about accented letters.

Please check the screenshot.

WinMerge-new-Installer-CP1152

**Comment by sdottaka** [comment]
Thank you for the confirmation.

**Pull request merged**
