### PR TITLE
Update Italian language resources (readme/install/shell extension/GUI)

### PR DESCRIPTION
**Pull request by bovirus**

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you!

**Comment by bovirus** [comment]
@sdottaka 

Seems that there si a problem regarding installation of localized Readme text file.

the installer code

;Documentation
Source: ..\..\Docs\Users\ReadMe.txt; DestDir: {app}\Docs; Flags: comparetimestamp ignoreversion promptifolder; Components: Core

[Icons]
;Start Menu Icons
Name: {group}\{cm:ReadMe}; Filename: {app}\Docs\ReadMe.txt; IconFileName: {win}\NOTEPAD.EXE

In this ways also if you have differnt Readme for different language seems that the instalelr install only Readnme (English).

**Comment by sdottaka** [comment]
I think it has been fixed by commit 73b08d8

**Comment by bovirus** [comment]
@sdottaka 

Where can I download latest instalelr build to test it?

**Comment by sdottaka** [comment]
We use AppVeyor, which automatically builds the installer when pushing source changes to the Bitbucket repository.
The latest installer is available at https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts.

**Comment by bovirus** [comment]
@sdottaka 

Two problem founds in the latest build of the installer.

The "Readme" (Italian) file at the end of the installation is showed wrongly about accented letters.
Please check if should be in ANSI or UTF-8 text coding (English file sue UTF-8 - not English one use ANSI).

WinMerge 2 16 4 0 - Readme (Italian)
 
The program link for "Readme" file (with Italian language selecetd for the installer) in WinMerge program group point to "Readme-Italian.txt" file that is not included in the program folder (sub-folder "Docs).

Quite strange because it show me before to close the installer.

**Comment by sdottaka** [comment]
The problem has been fixed by commit 9354aab39bf1a0b559cc759ffca52393267a3764.

**Comment by bovirus** [comment]
@sdottaka 

First problem (accented letter in readme italian) fixed.

**_Seconf problem not fixed._**

If I click on Leggimi (Readme Italian) it reported "Readme-Italian,.txt" not found,.
The installer didn't copy "Readme-Italian.txt" in "Doc" subfolder in Winmerge program directory.

**Comment by sdottaka** [comment]
Sorry I missed it.
The second problem has been fixed by commit 80b5e2d6853599aa639e00b1182c95c8c4bc4aaa

**Comment by bovirus** [comment]
@sdottaka 

Thanks. The latest build works fine.

**Pull request merged**
